### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by amanuel1995** [amanuel1995/MI-449-SS17-741-html-boilerplate-linting-and-code-style-uRxwab#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://amanuel1995.github.io/MI-449-SS17-741-html-boilerplate-linting-and-code-style-uRxwab/) and meets the following criteria:

- [x] The files from your last project are copied and pasted into the directory for this project
- [x] Your code returns no errors (warnings are OK) when pasted into the [W3C Validator](https://validator.w3.org/#validate_by_input) (this will also be expected for all future projects)
- [x] Consistent spacing and indentation are used on every line (this will also be expected for all future projects)
- [x] `skeleton.css` is used to improve the design of the page

**Comment by KatieMFritz** [comment]
Great job including `skeleton.css` and with indentation - everything is indented just right. 💯 The HTML is valid, as well. 

### Inconsistent Spacing

Within and between lines, you have some inconsistent spacing. For example:
* some of your headings have a line break below them, and others don't
* no line break after `<head>`, but a line break before `</head>`
* spaces after the opening `<p>` tag here, but not before the closing `</p>` tag: 
```<p> <em>sample_email@server.com  | +1-000-000-0000  | East Lansing, MI</em></p>```

Check out the _Consistent Spacing_ section on [page 3 of the lesson](https://msu.lansing.codes/courses/MI-449-SS17-741/lessons/html-boilerplate-linting-and-code-style/3) for examples of consistent and inconsistent spacing.  You can make up your own standards for spacing, but it's important to stick to them throughout a project so your code is easier for others (and your future self!) to read and understand. 

Let me know when you've made changes - and as always, if you have any questions along the way. 😸

**Comment by KatieMFritz** [comment]
By the way, I noticed you used a shortened URL ([https://goo.gl/RQIU2q](https://goo.gl/RQIU2q)) for your `skeleton.css` link, instead of the full CDN link. It works in this project, and I _think_ it's fine. Tagging @chrisvfritz just to make sure. Chris, any unforeseen consequences with using shortlinks to CDN resources?

**Comment by KatieMFritz** [comment]
@amanuel1995 This doesn't affect your project being approved, but looking at your [commit history](https://github.com/amanuel1995/MI-449-SS17-741-html-boilerplate-linting-and-code-style-uRxwab/commits/master), I have some comments about your git commits.

First of all, looks like you committed after each major change! That's a fantastic habit. :smile: The beauty of git is that by making regular commits, you give yourself lots of "save points." If you mess up later, you can go back to when it was working.

### Why we use unique commit messages

This is a lot easier if each commit has a unique message explaining what changed in that commit. However, for this project (and maybe previous projects too?), you used the same commit message ("HTML Valid Mark Ups Enforced") every time. If you needed to go back to a previous commit, you'd have to look at your code to figure out what changed, instead of being able to tell quickly from the commit log. 

From what I can tell from your code, here are some commit messages I might have used for this project:
1. "add code from previous project"
2. "update indentation to be consistent"
3. "add link to skeleton.css"
4. (upcoming commit) "update spacing to be consistent"

Do those make sense to you?

You don't have to worry about redoing any of this - but in the future, try giving each commit its own specific message describing what you just changed. It will help you be even more of a git wizard. 💪

**Comment by chrisvfritz** [comment]
> Chris, any unforeseen consequences with using shortlinks to CDN resources?

Great question! I'd avoid it, for 3 reasons:

1. It's more difficult to tell in your code what you're linking to.
2. Your page styles will load more slowly, because it has to first check in with `goo.gl`, _then_ be redirected to the original link.
2. It's one more point of failure. If the shortlink services goes down (which happens rarely, but sometimes), these styles won't load.

**Comment by amanuel1995** [comment]
Thank you @chrisvfritz  and @KatieMFritz for your detailed comments and suggestions. I think I have corrected the inconsistency on the spacings. I also have unshortened the URL for the CSS file. Let me know if there are things I still didn't notice or fulfill. 

Thank you!

**Comment by KatieMFritz** [comment]
Awesome - you're super close! Great job making more specific commit messages too. 👍 

One tiny change left:

You have a line break before the closing `</html>` but not after the opening `<html>`. Either add a line break to the beginning, or remove the one at the end (and also between `</head>` and `<body>`, if you go that direction).

**Comment by amanuel1995** [comment]
Did it. 😄

**Comment by KatieMFritz** [comment]
YES! 🎉 🎉 🎉 

I feel really invested in this project now. 😆 

:shipit:

**Comment by amanuel1995** [comment]
Thank you, am learning a lot and am happy I enrolled 😄 !
